import {
  CalendarCheck2,
  CheckSquare,
  Sparkles,
  Lock,
  Bell,
  Mic,
  TrendingUp,
} from 'lucide-react';

export const featureCards = [
  {
    title: 'Routine Mapping',
    description: 'Analyzes class schedule and sleep to find real free-time windows.',
    icon: CalendarCheck2,
    accent: 'from-cyan-400 to-blue-500',
    ring: 'ring-cyan-500/20',
    iconClassName: 'text-cyan-600',
    badge: 'Schedule aware',
  },
  {
    title: 'Micro-Tasks',
    description: '15-30 minute concept-complete tasks from your placement roadmap.',
    icon: CheckSquare,
    accent: 'from-emerald-400 to-teal-500',
    ring: 'ring-emerald-500/20',
    iconClassName: 'text-emerald-600',
    badge: 'Short sprints',
  },
  {
    title: 'Adaptive Motivation',
    description: 'Supportive, neutral, or strict style prompts based on your preference.',
    icon: Sparkles,
    accent: 'from-fuchsia-400 to-pink-500',
    ring: 'ring-fuchsia-500/20',
    iconClassName: 'text-fuchsia-600',
    badge: 'Mood matched',
  },
  {
    title: 'Lock-In Mode',
    description: 'Manual deep-focus sessions with chained tasks and stronger nudges.',
    icon: Lock,
    accent: 'from-amber-400 to-orange-500',
    ring: 'ring-amber-500/20',
    iconClassName: 'text-amber-600',
    badge: 'Focus control',
  },
  {
    title: 'Smart Reminders',
    description: 'Triggered by free time, never spam. Always contextual and useful.',
    icon: Bell,
    accent: 'from-violet-400 to-indigo-500',
    ring: 'ring-violet-500/20',
    iconClassName: 'text-violet-600',
    badge: 'Contextual nudges',
  },
  {
    title: 'Progress Tracking',
    description: 'Shows forward movement and trends, with no backlog guilt.',
    icon: TrendingUp,
    accent: 'from-rose-400 to-red-500',
    ring: 'ring-rose-500/20',
    iconClassName: 'text-rose-600',
    badge: 'Momentum first',
  },
  {
    title: 'AI Mock Interviewer',
    description: 'Voice-enabled HR, technical, resume, and company rounds with instant feedback.',
    icon: Mic,
    accent: 'from-red-400 to-orange-500',
    ring: 'ring-red-500/20',
    iconClassName: 'text-red-500',
    badge: 'Interview ready',
  },
];
